name: kemey_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  cupertino_icons: ^1.0.0
  flutter_svg: ^2.0.10+1
  flutter_card_swiper: ^7.2.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansEthiopic
      fonts:
        - asset: assets/fonts/NotoSansEthiopic-Regular.ttf
        - asset: assets/fonts/NotoSansEthiopic-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansEthiopic-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Goia
      fonts:
        - asset: assets/fonts/Goia-Regular.otf
        - asset: assets/fonts/Goia-Medium.otf
          weight: 500
  assets:
    - .env
    - assets/icons/
    - assets/tigrinya_fidel.json
